[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32G452RCTx"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=--nmagic",
  "-C", "linker=flip-link",
]

[build]
# Cortex-M4 (with FPU)
target = "thumbv7em-none-eabihf"
