name: Check Controller

on:
  push:
    paths:
      - ".github/workflows/check-controller.yaml"
      - "deuterium-controller/**"
  pull_request:
    paths:
      - ".github/workflows/check-controller.yaml"
      - "deuterium-controller/**"

defaults:
  run:
    working-directory: deuterium-controller

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: thumbv7em-none-eabihf
      - name: Check
        run: cargo check
